version: "3.9"
services:
    ui:
        build: ./
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        environment:
            - NODE_OPTIONS=--openssl-legacy-provider=value
